### ISSUE TITLE
Download of Ontology `.obo` fails . This causes an error when runnning jimzMlConverter

### ISSUE THREAD

**Issue by VolkerH** [AlanRace/imzMLConverter#10]
This is referring to the Release version `2.1.0` of the converter.
When trying to use the converter it produced the following error message (apologies for the screenshot, this was on a remote workstation so couldn't cut & paste the text):

![image](https://user-images.githubusercontent.com/2210044/150165982-ab7ce8d6-dc08-4fb2-8e5f-871c41233a31.png)

I tracked this down to some of the download URLs  for `.obo` ontology files not being valid anymore.
These are actually defined in another project (jimzMLParser):

https://github.com/AlanRace/jimzMLParser/blob/af30b68e71b8792d13cc026df37c46ab7e659815/src/main/java/com/alanmrace/jimzmlparser/obo/OBO.java#L26-L44

The `pato.obo` link in the source code above appears to be correct, but it appears the `imzMLParser.jar` that is bundled with the `2.1.0` is trying to download this file from a different URL which is now outdated.

I could restore functionality by adding the `.obo` files that were downloaded when doing a conversion in Sep 2021 to the `Ontologies` folder.

**Comment by AlanRace** [comment]
Hi,
This should be resolved in with the latest version (2.1.1). The URL in the `.obo` redirected to the correct location, but the code in `imzMLParser` was ignoring the redirect. 

Let me know if you have any other issues.

**Comment by VolkerH** [comment]
Thank you for fixing this so quickly, will give the new release a try.

**Comment by VolkerH** [comment]
@AlanRace 
Unfortunately, I still get the same error with the new release `2.1.1` now that I had a chance to try it out.
The only difference from traceback above is the line numbers for `loadOntologyFromFile` and `getObo`  in the traceback.
There still is a problem with the `pato.obo` file: 

![image](https://user-images.githubusercontent.com/2210044/150784870-2ac4ff4f-3734-453d-a5a4-6c92d9424d2d.png)
